spring:
  application:
    name: boat
  datasource:
    url: jdbc:mysql://localhost:3306/boat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
  redis:
    host: 47.102.97.161
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
    timeout: 2000ms
    database: 1
  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 端口
    port: 465
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: 1635732237@qq.com
    # 授权码
    password: hptuoqehvncvbgig
    # 其它参数
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          # 如果是用 SSL 方式，需要配置如下属性
          starttls:
            enable: true
            required: true


server:
  port: 9000



